### ISSUE TITLE
phf::map::get() returns `None` on a valid input in v0.7.21

### ISSUE THREAD

**Issue by RazrFalcon** [sfackler/rust-phf#102]
After updating to *.21 [my application](https://github.com/RazrFalcon/svgcleaner) stop working. You can download a snapshot from the [latest tag](https://github.com/RazrFalcon/svgcleaner/releases) to test it. I've already done a hotfix in the master (by downgrading to *.20).

The bug itself if [here](https://github.com/RazrFalcon/libsvgparser/blob/master/src/element.rs#L202). This method starts to return `None` on a valid input.

More details: https://github.com/RazrFalcon/svgcleaner/issues/72

**Comment by sfackler** [comment]
Did you rerun libsvgparser's codegen crate with the same version of phf?

**Comment by RazrFalcon** [comment]
No. Should I? I thought that it's final. Is it better to generate such files using build.rs because of changes like in *.21?

**Comment by sfackler** [comment]
Here is the diff upgrading postgres from 20 to 21: https://github.com/sfackler/rust-postgres/commit/17c53c967c4e6bc99301a53d74a556e235f60834.

It's fine to use codegen crates as long as you make sure the versions are pinned.

**Comment by RazrFalcon** [comment]
I didn't though that there will be breaking changes in a minor version, that's why i used `phf = "0.7.*"`.

I'll stick with a pinned version for now, but sadly my tagged release is broken now.

**Comment by sfackler** [comment]
The public facing API is stable within a minor version, but the internal representation is not.

**Comment by RazrFalcon** [comment]
In crates like this it's hard to tell which part is `internal representation`.

If this is not a bug, but an intended change - you can close it.

**Comment by sfackler** [comment]
The internal representation is specifically what's warned about here: https://github.com/sfackler/rust-phf/blob/master/phf/src/map.rs#L14-L16
