### ISSUE TITLE
Generation performance doesn't match README

### ISSUE THREAD

**Issue by joshtriplett** [sfackler/rust-phf#104]
The README says "It currently uses the CHD algorithm and can generate a 100,000 entry map in roughly .4 seconds.".

However, I tried building a 242415-entry `phf::Set<&'static str>` using phf_codegen, and it took 1092.68 seconds to build.

(The dataset came from `grep -E '^[a-z]{3,16}$' /usr/share/dict/words`, using the `/usr/share/dict/words` from http://ftp.us.debian.org/debian/pool/main/s/scowl/wamerican-huge_7.1-1_all.deb .)

**Comment by sfackler** [comment]
Are you maybe not building with optimizations? This program takes 2.48 seconds for me on OSX with a 235886 line dictionary:

```rust
extern crate phf_codegen;

use std::fs::File;
use std::io::{self, BufRead, BufReader};

fn main() {
    let mut builder = phf_codegen::Set::new();

    let file = BufReader::new(File::open("/usr/share/dict/words").unwrap());
    for word in file.lines() {
        let word = word.unwrap();
        builder.entry(word);
    }

    builder.build(&mut io::sink()).unwrap();
}
```

**Comment by joshtriplett** [comment]
That does make a substantial difference, thank you.  I changed the test program to actually write out the output rather than throwing it away, and the `builder.build` step ran in 685 seconds when compiled for debug, or ~16.8 seconds when compiled for release.

Could you document in README that release versus debug makes a massive performance difference in PHF generation?

This also provides further motivation for https://github.com/rust-lang/cargo/issues/2424 .

(As an aside, in the course of experimenting with this, I also found a serious performance issue in the rustc optimizer; I wrote a different test program that compiles in the word list, and it takes 30 seconds to compile in debug mode, but 20 minutes and counting in release mode.)
