### ISSUE TITLE
Integrate into compiler

### ISSUE THREAD

**Issue by ishitatsuyuki** [sfackler/rust-phf#105]
The match clause accepts any type of literal, which is syntaxically similar to phf maps. I feel we could simply code it in the compiler to make an intelligent match.

**Comment by sfackler** [comment]
This seems like an issue for rust-lang/rfcs rather than here?

**Comment by ishitatsuyuki** [comment]
I'm not sure if it should have a RFC, since it's completely transparent to the user.

**Comment by sfackler** [comment]
rust-lang/rust then maybe - in either case the decision that would be made is related to rustc not phf.

**Comment by ishitatsuyuki** [comment]
rust-lang/rust#39525

**Comment by sfackler** [comment]
Great, thanks!
