### ISSUE TITLE
add a specialized StringMap type for smaller code, especially in shared libraries

### ISSUE THREAD

**Issue by froydnj** [sfackler/rust-phf#107]
The current representation of `phf::Map` for string keys forces each entry in the map to have a pointer to some string data, which requires relocations in shared libraries and may force the entries to be larger than they need be, depending on alignment requirements.  (This is a common problem in C; I'm less sure if it applies to Rust, because I'm less familiar with what Rust does in this case.)

`gperf` includes the `--pic` option for dealing with this; entries in the map then contain integer offsets into a string pool, rather than character pointers.  The relocations are eliminated, resulting in smaller binaries, slightly improved startup performance, and potentially improving data sharing.  Additionally, the integer offset type can then be sized appropriately to the total size of the string pool, which may result in it being `u8`, `u16`, or `u32` as appropriate.  This last part is probably harder to do for `phf`, but I have found it useful for one-off tables.

Using C instead of Rust, the alignment requirements come about because you have the equivalent of:

```
struct entry {
  char* key;
  <enum type> value;
};
```

On x86-64, this requires 16 bytes regardless of the size of `enum type`.  If you can use an integer offset instead, you have:

```
struct entry {
  uint32_t key_offset;
  <enum type> value;
};
```

which fits into 8 bytes instead.  Depending on the precise size of `enum type`, you might be able to use a smaller type for `key_offset` and get the entry size down to 4 or so.  Maybe the wins for Rust would be more significant here, because `&'static str` are larger than a pointer?  Not sure on this.

**Comment by sfackler** [comment]
This seems like an interesting idea, but probably for another crate.
