### ISSUE TITLE
Can't use [u8] as a key with phf_codegen

### ISSUE THREAD

**Issue by njaard** [sfackler/rust-phf#110]
if I use phf_codegen to do the following:

    let mut set = phf_codegen::Set::new();
    set.entry(b"hello".to_vec());

Then its output looks like this:

    entries: phf::Slice::Static(&[
        ([104, 101, 108, 108, 111], ()),
    ]),

Which doesn't work because there needs to be a `&` before the array.

**Comment by sfackler** [comment]
phf_codegen currently just uses the `Debug` representation of the type, which should probably turn into a more specific trait here.

**Comment by njaard** [comment]
All of this seems to be a useful workaround:

```
#[derive(PartialEq, Eq, Ord, PartialOrd)]
struct WorkaroundBugInPhf
{
  data : Vec<u8>,
}

impl std::fmt::Debug for WorkaroundBugInPhf
{
  fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result
  {
    write!(f, "&{:?}", self.data)
  }
}

impl phf::PhfHash for WorkaroundBugInPhf
{
  fn phf_hash<H>(&self, state: &mut H)
    where H: std::hash::Hasher
  {
    phf::PhfHash::phf_hash(&self.data, state);
  }
}

impl std::hash::Hash for WorkaroundBugInPhf
{
  fn hash<H>(&self, state: &mut H)
    where H: std::hash::Hasher
  {
    std::hash::Hash::hash(&self.data, state);
  }
}

```
