### ISSUE TITLE
Panic in get_index if Map is empty

### ISSUE THREAD

**Issue by Bondza** [sfackler/rust-phf#111]
I was playing around with `phf_builder` and tried creating an empty `Map`. Like this:
```rust
extern crate phf;
extern crate phf_builder;
fn main() {
    let map: phf::map::Map<String, String> = phf_builder::Map::new().build();
    map.get("aaa");
}
```
It panics in `get`:
thread '<unnamed>' panicked at 'attempt to calculate the remainder with a divisor of zero', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_shared-0.7.21/src/lib.rs:46:26

**Comment by sfackler** [comment]
Fixed by #116.
