### ISSUE TITLE
code gen is much slower than macro on large sets

### ISSUE THREAD

**Issue by JuanPotato** [sfackler/rust-phf#125]
Trying to make a map for getting the names of unicode characters. When I do this with phf_macros, the ~31k items compile really quickly with the macros but extremely slowly with the code gen version. Is this a known downside to the code generation? The code in question is https://github.com/JuanPotato/unicode_bot here with the macro branch being for (you guessed it) the macro version.

It takes a few minutes to compile a debug version with code gen, but release never completes.

Honestly, if there's a better way that I should be doing this, I'd love to hear.

**Comment by sfackler** [comment]
What process is the one that takes forever? I'd expect it would be trying to compile the build script itself and the compiler is having trouble with a 31,000 line function. You could try moving the mapping into a separate file and having your build script loop over it.

**Comment by JuanPotato** [comment]
I'm not sure how to get the specific process, I just ran `cargo build --release` and it never finished. With putting it in a separate file, you mean something where the number and name are on each line separated by something and the build.rs just goes through and parses that to add them?

**Comment by sfackler** [comment]
Yeah - basically just having a JSON or csv or whatever file with the mapping and then iterate over that in your build.rs.

**Comment by JuanPotato** [comment]
Yeah that got it to compile. Release takes ~25s and debug ~10s. I guess rust for some unknown reason doesn't like tens of thousands of lines.
