### ISSUE TITLE
Bump rand dependency of phf_generator

### ISSUE THREAD

**Issue by kpcyrd** [sfackler/rust-phf#126]
Hey!

we ran into a problem with phf_generator while packaging it for debian (phf-shared was already [accepted][0]!). We noticed that it currently depends on rand 0.4, while we only have rand 0.5 in debian. Any chance you could release a new version that bumps this dependency? We're generally trying to avoid packaging outdated versions.

Thank you!

[0]: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=rust-phf

**Comment by Dr-Emann** [comment]
This was fixed with #127, isn't it?

**Comment by sfackler** [comment]
Ah yep!
