### ISSUE TITLE
PHF Map should own values

### ISSUE THREAD

**Issue by JacksonCoder** [sfackler/rust-phf#128]
Right now, the `phf::Map` struct doesn't actually own it's values, but instead stores a static slice of the values. This means that if `V` doesn't implement `Copy`, it can't be used as a value type, even when it is totally possible to use it as a value type if we made the `Map` struct store entries as `Box<[(K, V)]>`, instead of `&'static [(K, V)]`. Is there a reason a static slice is used instead of an owned array?

**Comment by sfackler** [comment]
Types that don't implement `Copy` can be used as value types. What is the behavioral difference you expect between storing a `Box<[(K, V)]>` instead of a `&'static [(K, V)]`?

> Is there a reason a static slice is used instead of an owned array?

You can't put a `Box` in a static.

**Comment by JacksonCoder** [comment]
> What is the behavioral difference you expect between storing a Box<[(K, V)]> instead of a &'static [(K, V)]?

You can't use a `String` as a value type in a PHF map. You can't create a `&'static [String]`, even using `lazy_static!`, but you can create a `Box<[String]>` just fine. You can't use `Box<T>` as a value type either (I think).

> You can't put a Box in a static.

I forgot about that! `lazy_static!` is a workaround, but that would require `V` to implement `Sync`.

**Comment by sfackler** [comment]
The reason you can't use String has nothing to do with Copy-ness - like Box, you can't construct a String in a static. The entire purpose of phf is to create a statically initialized map. If you're willing to use lazy_static you should just have a lazy_static HashMap. You can use `&'static str` rather than `String` in a phf map.

**Comment by JacksonCoder** [comment]
>The reason you can't use String has nothing to do with Copy-ness - like Box, you can't construct a String in a static.

You're right, I was mistaken in thinking that was related to incompatibility with the PHF map. I was testing usage of this map inside of a `lazy_static!` macro, and when I got the error `value does not live long enough` with values that can't be constructed in a static (like a String), I thought it was related to their lack of the Copy trait (because it worked fine with, say, a `u32`), forgetting that I was using `lazy_static!` in the first place.

I'll close this issue, as it's obviously not relevant to the crate, but I was wondering: the point of a PHF map is to create an immutable static map with pre-hashed fields to speed up runtime, right? I was thinking about making a `lazy-phf` crate that implemented a PHF map with owned values, made for maps with values that can't be initialized at compile time. Sort of like a regular PHF map, but wrapped in a `lazy_static!` definition and with a `Box<[(K, V)]>` instead of a `&'static [(K, V)]`. Do you think there would be any worthwhile speedup from this compared to a `lazy_static` HashMap?

**Comment by sfackler** [comment]
> the point of a PHF map is to create an immutable static map with pre-hashed fields to speed up runtime, right?

Lookups in a PHF map should be roughly the same speed as lookups in a normal HashMap - the main point is to have a statically allocated map.

**Comment by JacksonCoder** [comment]
> Lookups in a PHF map should be roughly the same speed as lookups in a normal HashMap - the main point is to have a statically allocated map.

Thanks for the clarification.
