### ISSUE TITLE
Attempting to use a u128 as a Map key results in "unsupported literal type"

### ISSUE THREAD

**Issue by kitlith** [sfackler/rust-phf#129]
Simple test case:
```rust
static SOME_MAP: phf::Map<u128, &'static str> = phf_map! {
    0u128 => "some string"
};
```
Note that everything appears to work if I change both instances of u128 to u64.

**Comment by abonander** [comment]
This crate just generally needs to have 128-bit integer support added. This is pretty straightforward:

* Add `delegate_debug!(u128)` and `delegate_debug!(i128)` here: https://github.com/sfackler/rust-phf/blob/27f7c2c85efde7aeb3c5409985f2d605aff8e05b/phf_shared/src/lib.rs#L90-L101
* Add `sip_impl!(le u128)` and `sip_impl!(le i128)` here: https://github.com/sfackler/rust-phf/blob/27f7c2c85efde7aeb3c5409985f2d605aff8e05b/phf_shared/src/lib.rs#L187-L195
* Add `U128` and `I128` variants to `ParsedKey` here: https://github.com/sfackler/rust-phf/blob/master/phf_macros/src/lib.rs

**Comment by abonander** [comment]
#155 opened
