### ISSUE TITLE
Upgrade Unicase

### ISSUE THREAD

**Issue by abonander** [sfackler/rust-phf#143]
It appears that support for Unicase was dropped at one point and then restored later. Do you intend to maintain support for it? If so, it would be nice to upgrade to ^2.0.

I have a pending PR to Unicase to mark some constructors `const` which should make it usable again: https://github.com/seanmonstar/unicase/pull/28

cc https://github.com/abonander/mime_guess/issues/37

**Comment by sfackler** [comment]
The blocker on the upgrade historically was the lack of const constructors. I also didn't think that anyone was still using unicase stuff with phf, but if it is actually used we can add back support.

**Comment by abonander** [comment]
I've been using the two together in `mime_guess` for a couple years now.

I saw your PR to remove it January of last year but it seems to have been reverted in master.

**Comment by abonander** [comment]
`unicase 2.3` should have the const constructors when it's published.

**Comment by abonander** [comment]
@sfackler the API of `phf_codegen` assumes that the debug representation of a struct is also a valid constructor, so that's not really gonna work. Perhaps instead of using `fmt::Debug` we should add a new trait with a method that returns a string to construct the given value (or add this to `PhfHash`)?

**Comment by sfackler** [comment]
Yep, that's one of the changes I was planning to make in a new major version anyway.

**Comment by abonander** [comment]
Would you accept a PR or do you prefer bikeshedding a bit first?
