### ISSUE TITLE
Compile time key checking

### ISSUE THREAD

**Issue by shanemikel** [sfackler/rust-phf#147]
Rustc has built-in support for compile-time index checking for statically sized arrays.

The following example doesn't compile, and prints an error that `2` is an out-of-bounds index for `MAP`.  It seems in principle that this would be possible to do with static PHF maps as well.

```rust
#![feature(proc_macro_hygiene)]

use phf::{ phf_map };

static ARR: [i32; 3] = [1, 2];
static MAP: phf::Map<&'static str, i32> = phf_map! {
    "one" => 1,
    "two" => 2,
};

fn main() {
    println!("arr[0] = {}", ARR[2]);
    println!("MAP[\"one\"] = {}", MAP["three"]);
}
```

**Comment by sfackler** [comment]
There is no way to do that in the language.

**Comment by shanemikel** [comment]
I suspect it may be somehow possible, but probably require a complete redesign of PHF, and definitely requires proc_macro (probably requires using a macro instead of the subscript operator).  Of course, I'm not all that experienced in Rust macro programming.

**Comment by shanemikel** [comment]
I'll close this for now
