### ISSUE TITLE
How do I use phf_codegen with the key being a byte string? (create example)

### ISSUE THREAD

**Issue by epage** [sfackler/rust-phf#151]
I'm not finding any docs or examples that cover various kinds of keys, particularly byte strings.

When I take my input string and do `as_bytes` on it into `entry` I get the following errors
```
error[E0308]: mismatched types
    --> /home/epage/git/defenestrate/target/debug/build/defenestrate-73941c0b26a3ba8c/out/codegen.rs:6834:10
     |
6834 |         ([109, 105, 115, 100, 101, 109, 101, 97, 110, 101, 114], "misdemeanor"),
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |          |
     |          expected &[u8], found array of 11 elements
     |          help: consider borrowing here: `&[109, 105, 115, 100, 101, 109, 101, 97, 110, 101, 114]`
```

**Comment by abonander** [comment]
This is a bug that I missed in my refactor. For slices, this impl needs to add a leading `&` so reference coercion works properly:

https://github.com/sfackler/rust-phf/blob/master/phf_shared/src/lib.rs#L84

**Comment by abonander** [comment]
#156 opened but it may be a breaking change.

**Comment by FreeMasen** [comment]
I am not sure that #156 does fix this issue.

Here is the example from the readme using byte strings

https://github.com/FreeMasen/phf_byte_str

I am still getting the following error when I try and use a byte string as a key
```
error[E0308]: mismatched types
  --> build.rs:15:16
   |
15 |         .entry(b"continue", "Keyword::Continue")
   |                ^^^^^^^^^^^ expected an array with a fixed size of 4 elements, found one with 8 elements
   |
   = note: expected type `&[u8; 4]`
              found type `&'static [u8; 8]`
```

**Comment by abonander** [comment]
That's really strange. Can you post the generated code as a gist or something?

**Comment by abonander** [comment]
@FreeMasen the problem is that the type of the `phf_codegen::Map` you're building there is inferred to be `phf_codegen::Map<&'static [u8; 4]>` because of the first `.entry(b"loop", ...)` call. Byte string literals produce references to fixed-sized arrays by default, there's nothing to tell the compiler to coerce the type to a slice. This works:

```rust
phf_codegen::Map::<&[u8]>::new() // explicitly specify the key type as byte slices
        .entry(b"loop", "Keyword::Loop")
        .entry(b"continue", "Keyword::Continue")
        .entry(b"break", "Keyword::Break")
        .entry(b"fn", "Keyword::Fn")
        .entry(b"extern", "Keyword::Extern")
        .build(&mut file)
        .unwrap();
```

There's also a couple errors in `src/main.rs`, firstly that the `vec![]` needs the same treatment:
```rust
let keys: Vec<&[u8]> = vec![
        b"loop",
        b"continue",
        b"break",
        b"fn",
        b"extern",
    ];
```

And secondly `parse_keyword` is marked `pub` when `Keyword` is not `pub`; you can't have a private type in a public function header.

**Comment by FreeMasen** [comment]
Awesome, thanks for the clarification!

**Comment by abonander** [comment]
I'm going to leave this issue open for now as a reminder to create an example for this.
