### ISSUE TITLE
Make clippy happy with long literal

### ISSUE THREAD

**Issue by calixteman** [sfackler/rust-phf#153]
I generate maps with phf_codegen and clippy is emitting warning:
```bash
warning: long literal lacking separators
   --> src/language_c.rs:461:10
    |
461 |     key: 3213172566270843353,
    |          ^^^^^^^^^^^^^^^^^^^ help: consider: `3_213_172_566_270_843_353`
    |
    = note: #[warn(clippy::unreadable_literal)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal
```
So it'd be nice to add seps.

**Comment by abonander** [comment]
Code generated by this crate isn't really meant to be read by humans so I'm not sure what supporting this would add. It would just be easier to `#[allow()]` that lint for the generated module.

**Comment by JohnTitor** [comment]
Closing in favor of the above comment.
