### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by abonander** [sfackler/rust-phf#154]
@sfackler Is there anything blocking an 0.8 release? Any issues that need to be closed or PRs that need to be merged?

**Comment by sfackler** [comment]
I unfortunately don't have a ton of time to devote to this crate (as you've probably noticed by now 😞). Would you be interested in helping to run things? I can add you as a collaborator on the repo if so!

**Comment by abonander** [comment]
Sure, I'd be glad to help out.

**Comment by sfackler** [comment]
Awesome, thanks! Just sent you invites for Github and crates.io publish.

**Comment by vasilakisfil** [comment]
any update on the release ?

**Comment by dignifiedquire** [comment]
any news on this?

**Comment by abonander** [comment]
I was waiting for feedback on #174 since it could break some things.

**Comment by nox** [comment]
I'm currently trying to get rid of `rand` 0.6 in Servo so it would be quite appreciated if you could at least release a new `phf_generator` version.

@abonander What do you think?

**Comment by abonander** [comment]
I have opened a release PR #180; I'll merge it and publish later today.

**Comment by abonander** [comment]
`0.8.0` published
