### ISSUE TITLE
Borrow trait is overly restrictive for lookups

### ISSUE THREAD

**Issue by abonander** [sfackler/rust-phf#169]
This kind of necros #8 but the context is different; essentially, it's kind of difficult to use `UniCase<&'static str>` as a key because you can only do lookups with `UniCase<&'static str>`:

```rust
fn get_key(map: &'static phf::Map<UniCase<&'static str>, ()>) {
    let key = String::new();
    map.get(&UniCase::new(&*key));
    //       ---------------^^^
    //       |              |
    //       |              borrowed value does not live long enough
    //       argument requires that `key` is borrowed for `'static`
}
```

As far as I can tell this is entirely due to the `K: Borrow<T>` bound on `Map` *et al* because the compiler thinks the following line means `T` needs to live as long as `K`:

https://github.com/sfackler/rust-phf/blob/50c6c75d406b529601f0377afba93e562bbff2aa/phf/src/map.rs#L87

If you change the bounds to `T: PartialEq<K> + PhfHash` the above compiles but that changes the semantics slightly since it's going through different traits but I believe it's actually less restrictive because it's impossible to generically implement `Borrow<Foo<U>> for Foo<T>` without unsafe while `PartialEq<Foo<U>> for Foo<T>` is perfectly fine. (This also means looking up with `UniCase` would work regardless of the string type being used.)

cc @sfackler

**Comment by abonander** [comment]
@sfackler if you're okay with this change I'll open a PR implementing it so it can be part of 0.8.

**Comment by sfackler** [comment]
It feels a bit bad to deviate from the normal approach collections take, but this does seem to be a different enough case to be worth it.

**Comment by abonander** [comment]
I don't actually know the reasoning for using `Borrow` in the original collections either, honestly. I guess to always use `Eq` instead of `PartialEq`?

**Comment by sfackler** [comment]
It's that and a requirement that the Hash implementations agree.

**Comment by abonander** [comment]
Well that's not even being guaranteed currently since we're invoking `hash` on `T` and comparing it to the hash generated by `K`; there's nothing in the `Borrow` trait's semantics that says the borrowed type must produce the same hash result as the owned type.

**Comment by sfackler** [comment]
> In particular Eq, Ord and Hash must be equivalent for borrowed and owned values: x.borrow() == y.borrow() should give the same result as x == y.

https://doc.rust-lang.org/std/borrow/trait.Borrow.html

**Comment by abonander** [comment]
That seems superfluous since if `Hash` returns the same value for instances of `T` and `K` respectively, and `PartialEq<K> for T` returns `true` for those instances, then we must have found our hashmap entry, no? There's no unsoundness if those implementations aren't correct; the user just might get the wrong value or nothing. Maybe it serves as an anti-footgun but at the same time requiring `Borrow` precludes so many useful patterns.

**Comment by abonander** [comment]
@sfackler I ran into a problem switching to using `T: PhfHash + PartialEq<U>`. When looking up with slices we run into a problem where the `T` type is `[u8]` and the `K` type is `&'_ [u8]` because there's no `PartialEq` impl covering that. The `Borrow` bound gave us some variance when it came to references. I tried `&'_ T: PartialEq<K>` but that doesn't work either because that breaks the case where `T` and `K` are the same type.

What I'm thinking now instead is that we need a `PhfBorrow` trait that explicitly *doesn't* have a blanket impl so we can provide a `impl<'b, 'a: 'b> PhfBorrow<UniCase<&'b str>> for UniCase<&'a str> {}` to allow the original use-case I wanted to do this switch for.
