### ISSUE TITLE
phf fails on current Rust with "no `phf_map` in the root"

### ISSUE THREAD

**Issue by buzmeg** [sfackler/rust-phf#203]
The current version of phf fails with:

error[E0432]: unresolved import `phf::phf_map`
  --> src\main.rs:43:5
   |
43 | use phf::phf_map;
   |     ^^^^^^^^^^^^ no `phf_map` in the root

Thanks.

Edit:  I figured I should note that I do have "edition = "2018" in my package section.

>cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)

>rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Comment by chpio** [comment]
> Requires the "macros" feature.

**Comment by JohnTitor** [comment]
Closing in favor of the above comment.

**Comment by AnatolyBug** [comment]
@chpio could you elaborate? What is "macros" feature?
