### ISSUE TITLE
Support ASCII-case-insensitive keys

### ISSUE THREAD

**Issue by kmcallister** [sfackler/rust-phf#21]
@SimonSapin wanted this for CSS parsing. It could also be useful for HTML parsing.  It's pervasive in the Web platform and has a much simpler definition than Unicode case folding.

**Comment by SimonSapin** [comment]
This can now be done with a wrapper type that implements `Eq` and `PhfHash`, and `Borrow` appropriately. However the current design of `PhfMap` makes it difficult to implement it for this without allocating as it doesn’t enable generating one at a time the bytes to be hashed.
