### ISSUE TITLE
Support non literal keys

### ISSUE THREAD

**Issue by pyfisch** [sfackler/rust-phf#43]
Hello,

 is it possible to support keys that are no literals? I try to implement parsing from string to enum variants (works with phf), and formatting the enum variants back to string also with phf (does not work).

```rust
static LANGUAGE_FROM_STR: phf::Map<&'static str, Language> = phf_map! {
    "ar" => Language::Ar,
    "de" => Language::De,
    "en" => Language::En,
    "fr" => Language::Fr,
    "sl" => Language::Sl,
};

// The signature is probably wrong
static STR_FROM_LANGUAGE: phf::Map<Language, &'static str> = phf_map! {
    Language::Ar => "ar",
    Language::De => "de",
    Language::En => "en",
    Language::Fr => "fr",
    Language::Sl => "sl",
};
```

The error:
```
src/language.rs:26:5: 26:17 error: expected a literal
src/language.rs:26     Language::Ar => "ar",
                       ^~~~~~~~~~~~
src/lib.rs:1:1: 462:1 note: in expansion of phf_map!
src/language.rs:25:62: 31:3 note: expansion site

...
```

**Comment by sfackler** [comment]
It's very difficult if not impossible to handle non-literal keys. The macro doesn't get enough information about the `Language` type at compile time to be able to deal with it.

On the other hand, there's no reason to use rust-phf to map from enum variants to something. There's already a trivial perfect hash function defined on variants: the discriminants. Make a function with a big match statement and you should be good to go.

**Comment by pyfisch** [comment]
I came to phf to avoid big match statements. It takes really to both run and compile a match statement with 8000 entries. But it is possible to use `Language` in static structs, so I think it should be possible to also use it in pfh. So I will have to look for a different solution.

**Comment by sfackler** [comment]
You can probably get this to work now with the new `phf_codegen` package, though you'll have to be careful to make sure your type hashes the same at build time and run time: http://sfackler.github.io/rust-phf/doc/phf_codegen/index.html

**Comment by pyfisch** [comment]
Sorry it took quite a while for me to come back to language tags.

I updated [rust-language-tags](https://github.com/pyfisch/rust-language-tags) today. The `from_str` already uses phf, next comes the `Display` trait method which will use non-literal keys. Since I never used a build script with rust before it may take some more days until it works.

**Comment by sfackler** [comment]
Cool. There's a small test crate you can reference if that'd help: https://github.com/sfackler/rust-phf/tree/master/phf_codegen/test
