### ISSUE TITLE
 method `Iter` is not a member of trait `IntoIterator`

### ISSUE THREAD

**Issue by gra** [sfackler/rust-phf#46]
Compiling phf v0.6.5
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/map.rs:133:10: 133:35 error: method `Iter` is not a member of trait `IntoIterator`
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/map.rs:133     type Iter = Entries<'a, K, V>;
                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/set.rs:104:10: 104:29 error: method `Iter` is not a member of trait `IntoIterator`
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/set.rs:104     type Iter = Iter<'a, T>;
                                                                                            ^~~~~~~~~~~~~~~~~~~
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/ordered_map.rs:152:10: 152:35 error: method `Iter` is not a member of trait `IntoIterator`
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/ordered_map.rs:152     type Iter = Entries<'a, K, V>;
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/ordered_set.rs:115:10: 115:29 error: method `Iter` is not a member of trait `IntoIterator`
/home/gra/.cargo/registry/src/github.com-1ecc6299db9ec823/phf-0.6.5/src/ordered_set.rs:115     type Iter = Iter<'a, T>;
                                                                                                    ^~~~~~~~~~~~~~~~~~~
error: aborting due to 4 previous errors

**Comment by sfackler** [comment]
Fixed in v0.6.6
