### ISSUE TITLE
phf on crates.io needs update

### ISSUE THREAD

**Issue by Ogeon** [sfackler/rust-phf#52]
`phf_generator` is incompatible with the latest nightly, due to old `rand`. It's still using 0.1.

**Comment by sfackler** [comment]
Waiting on https://github.com/rust-lang/rand/issues/32

**Comment by Ogeon** [comment]
Oh, I'm blind. It's the same error as for 0.1.4, and I see now that I received it for both versions of `rand`. An update would still be nice :)

**Comment by sfackler** [comment]
Published v0.6.15

**Comment by Ogeon** [comment]
Thank you :)
