### ISSUE TITLE
Integer literal keys

### ISSUE THREAD

**Issue by nham** [sfackler/rust-phf#57]
Do integer literal keys not work? I tried to change the example the readme to:

    static KEYWORDS: phf::Map<u8, Keyword> = phf_map! {
        3 => Keyword::Loop,
        4 => Keyword::Continue,
        5 => Keyword::Break,
        6 => Keyword::Fn,
        7 => Keyword::Extern,
    };

But it yields errors:

    src/main.rs:16:5: 16:6 error: unsupported literal type
    src/main.rs:16     3 => Keyword::Loop,
                       ^
    src/main.rs:1:1: 28:1 note: in expansion of phf_map!
    src/main.rs:15:42: 21:2 note: expansion site
    src/main.rs:17:5: 17:6 error: unsupported literal type
    src/main.rs:17     4 => Keyword::Continue,
                       ^
    src/main.rs:1:1: 28:1 note: in expansion of phf_map!
    src/main.rs:15:42: 21:2 note: expansion site
    src/main.rs:18:5: 18:6 error: unsupported literal type
    src/main.rs:18     5 => Keyword::Break,
                       ^
    src/main.rs:1:1: 28:1 note: in expansion of phf_map!
    src/main.rs:15:42: 21:2 note: expansion site
    src/main.rs:19:5: 19:6 error: unsupported literal type
    src/main.rs:19     6 => Keyword::Fn,
                       ^
    src/main.rs:1:1: 28:1 note: in expansion of phf_map!
    src/main.rs:15:42: 21:2 note: expansion site
    src/main.rs:20:5: 20:6 error: unsupported literal type
    src/main.rs:20     7 => Keyword::Extern,
                       ^
    src/main.rs:1:1: 28:1 note: in expansion of phf_map!
    src/main.rs:15:42: 21:2 note: expansion site
    error: aborting due to 5 previous errors

Am I doing something wrong or is it genuinely not supported? If the latter, can it be documented which key types are supported? I could not find it in the documentation (though I apologize if it's there and I missed it).

**Comment by sfackler** [comment]
`phf_map!` needs to be passed suffixed integer literals so it knows what integer type to use. Change it to `3u8` etc and it'll work.

**Comment by nham** [comment]
Doh. should've tried that. Thanks.

**Comment by schungx** [comment]
Is there a way to avoid having to add `_u8` or `_u32` to every number as the key?

**Comment by N1ckn1ght** [comment]
> `phf_map!` needs to be passed suffixed integer literals so it knows what integer type to use. Change it to `3u8` etc and it'll work.

Is there a way to use **usize** key?

**Comment by DavidHospital** [comment]
> Is there a way to use usize key?
Anyone know how to do this?
