### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by gz** [sfackler/rust-phf#67]
I noticed that no_std support was removed in https://github.com/sfackler/rust-phf/commit/d4c189a2b060df33e7c97d6c1f0f430b68fc23b5. Is there any particular reason for that change? The commit message hints at SipHash not beeing available in libcore but AFAICT it seems to be there (https://github.com/rust-lang/rust/blob/master/src/libcore/hash/sip.rs)?

**Comment by sfackler** [comment]
There was a lot of movement of modules between core and the other crates in the lead up to 1.0, and at one point SipHash wasn't in libcore. I think the world's in a better place now, so I'd be totally on board with adding no_std support.
