### ISSUE TITLE
phf_map! cannot be used with &'static [u8] keys

### ISSUE THREAD

**Issue by nox** [sfackler/rust-phf#76]
```rust
tests/test.rs:20:63: 22:6 error: mismatched types:
 expected `phf::map::Map<&'static [u8], &'static str>`,
    found `phf::map::Map<&[u8; 9], &str>`
(expected slice,
    found array of 9 elements) [E0308]
tests/test.rs:20     static SLICE_KEY: phf::Map<&'static [u8], &'static str> = phf_map!(
tests/test.rs:21         b"camembert" => "delicious",
tests/test.rs:22     );
```

**Comment by SimonSapin** [comment]
Does this work?

```rust
static SLICE_KEY: phf::Map<&'static [u8], &'static str> = phf_map!(
    b"camembert" as &[u8] => "delicious",
);
```

**Comment by nox** [comment]
It does. But the macro cannot generate that cast unconditionally, user could be trying to make a map from FourCC codes or whatever, in which cases the key type would be `[u8; 4]`.

**Comment by nox** [comment]
Oh sorry, you were talking of passing that to the macro directly; that's not allowed currently.

**Comment by nox** [comment]
Wouldn't it be silly to use a map or set with key type `&[u8; N]` instead of `[u8; N]`?

Given that `b"foo"` has type `&[u8; 3]`, I wonder if we could unconditionally add a `as &[u8]` cast to byte string literals in `phf_macros`.

**Comment by nox** [comment]
https://github.com/rust-lang/rust/issues/31260 should fix that problem, actually.

**Comment by sfackler** [comment]
Yeah, adjusting the expansion of the `b"foo"` case seems appropriate for now.
