### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Moredread** [sfackler/rust-phf#85]
From the bench it seems like there is no performance gain compared to hash maps and matching is still faster.

Have you done benchmarks that illustrate a performance gain? I couldn't find anything on this in the Readme or the docs.

**Comment by sfackler** [comment]
I would expect performance to be almost identical to a hash map - this library uses the same hashing algorithm as `HashMap`'s default, and there's just a trivial amount of lookup after that in both cases.

I would expect a match to be more efficient for many cases with integral types, but that is not the case for strings, which was the original impetus for the creation of this library. Rust compiles matches over strings into a if-else-if-else style chain of memcmps, which for large enums like http://sfackler.github.io/rust-postgres/doc/v0.11.8/postgres/error/enum.SqlState.html#method.from_code is a *lot* of string comparison. I believe html5ever uses this library for a similar purpose with a table of ~thousands of entries.

**Comment by Moredread** [comment]
I'm not quite clear what the use case of rust-phf is then. Is it the lower cost of creating the map at runtime, as the work is already done at compile time?

**Comment by sfackler** [comment]
The use case vs a hash map? Yep, it'd avoid the runtime cost of construction.

**Comment by sfackler** [comment]
Particularly when this library was created, I don't believe that lazy_static existed so using a normal HashMap wasn't even really an option.

**Comment by Moredread** [comment]
Thank you for your answer, now it's bit clearer for me :)

**Comment by tmm1** [comment]
See also https://users.rust-lang.org/t/why-is-phf-map-slower-than-std-hashmap/97339/3

In my experience, using four Sets sized ~50-200k items each, phf was slower than an existing implementation using rustc-hash

```
time:   [1.7673 ms 1.7735 ms 1.7803 ms]
time:   [4.3551 ms 4.3616 ms 4.3718 ms]
change: [+143.40% +144.57% +145.60%] (p = 0.00 < 0.05)
Performance has regressed.
```
