### ISSUE TITLE
Support for syntex in phf code generation on stable

### ISSUE THREAD

**Issue by Protagores** [sfackler/rust-phf#86]
The crate [serde-rs/syntex](https://github.com/serde-rs/syntex) provides basically the same functionality as libsyntax but can be used with stable Rust, so that more tidy macros could be expanded by a unified build script instead of current codegen approach, when the entries are hard-coded into build.rs itself.

Can the phf_macros crate possibly be made to use syntex on stable Rust?

**UPDATE:** It appears that serde actually uses syntex in serde_codegen, not serde_macros crate. So maybe it's plausible to use syntex to make phf_codegen parse the same input files as with phf_macros.

**Comment by abonander** [comment]
`phf_macros` uses `syn` now so this issue isn't really relevant anymore.
