### ISSUE TITLE
Hash for ASCII data

### ISSUE THREAD

**Issue by RazrFalcon** [sfackler/rust-phf#90]
Hello.

I need lookup for ASCII data only. I think that &str has some overhead, but I can't test it. Simply changing `&'static str` to `&'static [u8]` produce lots of compiler errors. Also it writes data to codegen.rs as array, not as b"text".

It it possible? 

PS: I'm using phf_codegen on stable rustc.

**Comment by sfackler** [comment]
What overhead are you concerned about?

**Comment by RazrFalcon** [comment]
Lookup speed, memory consumption, binary/executable size. And in any way I only need `&[u8]`.

**Comment by sfackler** [comment]
`str` is just a `&[u8]` that is guaranteed to contain UTF-8 valid bytes. Comparison and hashing is identical to that of a `&[u8]`.

**Comment by RazrFalcon** [comment]
I thought `&str` is `&[u32]`... Strange. Probably because Char is u32.
Thanks for clearing this out.
