### ISSUE TITLE
[Servo release build] Could not find `symbol` in `syntax`

### ISSUE THREAD

**Issue by novaksam** [sfackler/rust-phf#97]
`
error[E0432]: unresolved import syntax::symbol::Symbol
  --> /Users/User/Documents/Sources/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_macros-0.7.20/src/lib.rs:57:5
|
57 | use syntax::symbol::Symbol;
|      ^^^^^^^^^^^^^^^^^^^^^^ Could not find symbol in syntax
`

`error[E0432]: unresolved import syntax::symbol::InternedString
 --> /Users/User/Documents/Sources/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_macros-0.7.20/src/util.rs:9:5
  |
9 | use syntax::symbol::InternedString;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find symbol in syntax
`

`
error: no method named as_str found for type &syntax::parse::token::InternedString in the current scope
   --> /Users/User/Documents/Sources/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_macros-0.7.20/src/lib.rs:242:64
    |
242 |                 ast::LitKind::Str(ref s, _) => Some(Key::Str(s.as_str())),
    |                                                                ^^^^^^
`

Just giving a heads up.

**Comment by sfackler** [comment]
Your nightly version is out of date.
